/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2;


import javax.swing.* ;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author JENNIFER
 */
public class MiniEditor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MiniEditor.class.getName());

    /**
     * Creates new form MiniEditor
     */
    public MiniEditor() {
        initComponents();
        setSize(500,400);
        setTitle("Ejercicio 2: Mini Editor de Texto");
        
        // Limpiar texto
       itemLimpiar.addActionListener(e -> {
        System.out.println("DEBUG: El botón fue presionado"); // Si ves esto en la consola, el botón sí funciona
        areaTexto.setText(""); 
    });
        
        // Salir
        itemSalir.addActionListener(e -> {
        System.exit(0); 
    });
    
        //Instanciar JMenu y fijarlo
        JMenuBar barraSuperior = new JMenuBar();
        setJMenuBar(barraSuperior);
        
        // JMenu lo llamamos Archivo y añadirlo
        JMenu menuArchivo = new JMenu("Archivo");
        barraSuperior.add(menuArchivo);
        
        
        // Añadims 2 opciones instanciado JMenuItem
        JMenuItem itemLimpiar = new JMenuItem("Limpiar texto");
        JMenuItem itemSalir = new JMenuItem("Salir");
        menuArchivo.add(itemLimpiar);
        menuArchivo.add(itemSalir);
        
        //Añadir en el centro de la ventana un JTextArea
        areaTexto = new JTextArea();
        JScrollPane scroll = new JScrollPane(areaTexto);
        
        setLayout(new BorderLayout());
        add(jScrollPane1, BorderLayout.CENTER);
        
        //Interacción: Asocia un ActionListener a cada JMenuItem
        //Limpiar texto 
        itemLimpiar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                areaTexto.setText(""); // Reemplaza el contenido por texto vacío
            }
        });
        
        //Salir
        itemSalir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0); // Código 0 significa "Cierre exitoso sin errores"
            }
        });
    
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemLimpiar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        menuArchivo.setText("Archivo");

        itemLimpiar.setText("Limpiar texto");
        menuArchivo.add(itemLimpiar);

        itemSalir.setText("Salir");
        menuArchivo.add(itemSalir);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MiniEditor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JMenuItem itemLimpiar;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuArchivo;
    // End of variables declaration//GEN-END:variables
}
